### ISSUE TITLE
$-sign in Markdown causes strange issue

### ISSUE THREAD

**Issue by jooize** [Daology/Support#4]
Markdown:

```
- [XenForo](https://xenforo.com/): $140+ with one year of upgrades, and $40 per each additional year.
```

Result:
![](https://cloud.githubusercontent.com/assets/719371/11004708/3331aad4-84ba-11e5-857a-a89bc446f976.png)

Removing the first ‘$’ makes it render correctly.

**Comment by brossi** [comment]
That is firing incorrectly because of the KaTeX parsing. I've got a working build that corrects it, though it requires that inline KaTeX be indicated by wrapping the equation text with `$[` and `]$` instead of `$` and `$`. I believe that it's a worthwhile trade-off, but if anyone has a contrary opinion, please let me know.

**Comment by brossi** [comment]
Actually, upon further consideration, I will use `$$` as the starting and ending indicator for inline equations and `$$$` for block displayed equations. The block delimiter has precedence because we use a triple backtick to denote the start and end of a block displayed code section.

Thank you for identifying this and I'll get a patch deployed shortly to address this.

**Comment by CoinGame** [comment]
This fix should be live on the site now. Let us know if there's any other issues.

**Comment by brossi** [comment]
Deployed as part of [1.2.1](https://github.com/Daology/Support/wiki/Release-History#v121)

**Comment by jooize** [comment]
Great, confirmed working! I will.
